package com.xiaonian.core.entity;

public class RoleStrategyKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_strategy.role_id
     *
     * @mbggenerated
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_strategy.strategy_id
     *
     * @mbggenerated
     */
    private Integer strategyId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_strategy.role_id
     *
     * @return the value of role_strategy.role_id
     *
     * @mbggenerated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_strategy.role_id
     *
     * @param roleId the value for role_strategy.role_id
     *
     * @mbggenerated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_strategy.strategy_id
     *
     * @return the value of role_strategy.strategy_id
     *
     * @mbggenerated
     */
    public Integer getStrategyId() {
        return strategyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_strategy.strategy_id
     *
     * @param strategyId the value for role_strategy.strategy_id
     *
     * @mbggenerated
     */
    public void setStrategyId(Integer strategyId) {
        this.strategyId = strategyId;
    }
}